#!/bin/bash

# Created by Elizabeth Swann

log=$HOME/.logs/DockerCleanup.log
date=$(date +%Y-%m-%d)

if [ ! -f $log ]; then
    touch $log
fi

echo "" >> $log
echo $date ": Start Log">> $log

{
    docker image prune -af >> $log 
    echo $date ": End Log" >> $log
} || {
    echo "Error, exiting." >> $log
    echo $date ": End Log" >> $log
    exit 1
}

exit 0