#!/usr/bin/env perl
use strict;
use warnings;

my $system = `uname -s`;
chomp($system);

if ($system =~ /Darwin/) {
    print "OS: macOS\n";
} elsif ($system =~ /Linux/) {
    print "OS: Linux\n";
} else {
    print "OS: Unknown\n";
}

my $kernel_version = `uname -r`;
chomp($kernel_version);
print "Kernel version: $kernel_version\n";

my @distribution = qw(Unknown);
if ($system =~ /Darwin/) {
    @distribution = ("macOS", "Mac OS X");
} elsif ($system =~ /Linux/) {
    @distribution = `lsb_release -d`;
    chomp(@distribution);
}
print "Distribution: $distribution[0]\n";

my $cpu_count = `cat /proc/cpuinfo | grep 'model name' | wc -l`;
chomp($cpu_count);
print "CPU count: $cpu_count\n";

my @ram = qw(Unknown);
if ($system =~ /Darwin/) {
    @ram = `sysctl -a | grep 'hw.memsize' | cut -d '=' -f 2`;
} elsif ($system =~ /Linux/) {
    @ram = `cat /proc/meminfo | grep MemTotal`;
}
chomp(@ram);
print "RAM: $ram[0] MB\n";