{
    "device": {
        "id": "c6fbff41-28bc-47dd-8913-8cbbf9b39ece",
        "is_active": true,
        "is_private_session": false,
        "is_restricted": false,
        "name": "Razorback",
        "type": "Speaker",
        "volume_percent": 70
    },
    "repeat_state": "off",
    "shuffle_state": false,
    "context": {
        "uri": "spotify:user:tbbk9yxfbpfmvhk51xarnr1rq:collection",
        "href": "https://api.spotify.com/v1/me/tracks",
        "external_urls": {
            "spotify": "https://open.spotify.com/collection/tracks"
        },
        "type": "collection"
    },
    "timestamp": 1738209601631,
    "progress_ms": 20239,
    "is_playing": true,
    "item": {
        "album": {
            "album_type": "single",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/01olvHW7uzIInQx9VTNuJm"
                    },
                    "href": "https://api.spotify.com/v1/artists/01olvHW7uzIInQx9VTNuJm",
                    "id": "01olvHW7uzIInQx9VTNuJm",
                    "name": "Rootkit"
                },
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/3ccMUmxnP7Poo48pJXu6X7"
                    },
                    "href": "https://api.spotify.com/v1/artists/3ccMUmxnP7Poo48pJXu6X7",
                    "id": "3ccMUmxnP7Poo48pJXu6X7",
                    "name": "Melano"
                }
            ],
            "available_markets": [
                "AR",
                "AU",
                "AT",
                "BE",
                "BO",
                "BR",
                "BG",
                "CA",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DK",
                "DO",
                "DE",
                "EC",
                "EE",
                "SV",
                "FI",
                "FR",
                "GR",
                "GT",
                "HN",
                "HK",
                "HU",
                "IS",
                "IE",
                "IT",
                "LV",
                "LT",
                "LU",
                "MY",
                "MT",
                "MX",
                "NL",
                "NZ",
                "NI",
                "NO",
                "PA",
                "PY",
                "PE",
                "PH",
                "PL",
                "PT",
                "SG",
                "SK",
                "ES",
                "SE",
                "CH",
                "TW",
                "TR",
                "UY",
                "US",
                "GB",
                "AD",
                "LI",
                "MC",
                "ID",
                "JP",
                "TH",
                "VN",
                "RO",
                "IL",
                "ZA",
                "SA",
                "AE",
                "BH",
                "QA",
                "OM",
                "KW",
                "EG",
                "MA",
                "DZ",
                "TN",
                "LB",
                "JO",
                "PS",
                "IN",
                "BY",
                "KZ",
                "MD",
                "UA",
                "AL",
                "BA",
                "HR",
                "ME",
                "MK",
                "RS",
                "SI",
                "KR",
                "BD",
                "PK",
                "LK",
                "GH",
                "KE",
                "NG",
                "TZ",
                "UG",
                "AG",
                "AM",
                "BS",
                "BB",
                "BZ",
                "BT",
                "BW",
                "BF",
                "CV",
                "CW",
                "DM",
                "FJ",
                "GM",
                "GE",
                "GD",
                "GW",
                "GY",
                "HT",
                "JM",
                "KI",
                "LS",
                "LR",
                "MW",
                "MV",
                "ML",
                "MH",
                "FM",
                "NA",
                "NR",
                "NE",
                "PW",
                "PG",
                "PR",
                "WS",
                "SM",
                "ST",
                "SN",
                "SC",
                "SL",
                "SB",
                "KN",
                "LC",
                "VC",
                "SR",
                "TL",
                "TO",
                "TT",
                "TV",
                "VU",
                "AZ",
                "BN",
                "BI",
                "KH",
                "CM",
                "TD",
                "KM",
                "GQ",
                "SZ",
                "GA",
                "GN",
                "KG",
                "LA",
                "MO",
                "MR",
                "MN",
                "NP",
                "RW",
                "TG",
                "UZ",
                "ZW",
                "BJ",
                "MG",
                "MU",
                "MZ",
                "AO",
                "CI",
                "DJ",
                "ZM",
                "CD",
                "CG",
                "IQ",
                "LY",
                "TJ",
                "VE",
                "ET",
                "XK"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/0DfZQ6EZGzYmNXH3kcwQEU"
            },
            "href": "https://api.spotify.com/v1/albums/0DfZQ6EZGzYmNXH3kcwQEU",
            "id": "0DfZQ6EZGzYmNXH3kcwQEU",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273f1713422cfd3d08fabfe9e36",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02f1713422cfd3d08fabfe9e36",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851f1713422cfd3d08fabfe9e36",
                    "width": 64
                }
            ],
            "name": "One More",
            "release_date": "2024-08-28",
            "release_date_precision": "day"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/01olvHW7uzIInQx9VTNuJm"
                },
                "href": "https://api.spotify.com/v1/artists/01olvHW7uzIInQx9VTNuJm",
                "id": "01olvHW7uzIInQx9VTNuJm",
                "name": "Rootkit"
            },
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3ccMUmxnP7Poo48pJXu6X7"
                },
                "href": "https://api.spotify.com/v1/artists/3ccMUmxnP7Poo48pJXu6X7",
                "id": "3ccMUmxnP7Poo48pJXu6X7",
                "name": "Melano"
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK"
        ],
        "disc_number": 1,
        "duration_ms": 243380,
        "explicit": false,
        "external_ids": {
            "isrc": "QZTB52427444"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/7rDsUfIlerrUC1B1lXuEy8"
        },
        "href": "https://api.spotify.com/v1/tracks/7rDsUfIlerrUC1B1lXuEy8",
        "id": "7rDsUfIlerrUC1B1lXuEy8",
        "is_local": false,
        "name": "One More",
        "popularity": 19,
        "preview_url": "https://p.scdn.co/mp3-preview/0b7158896e558e2293313242d002b046dc69fc6a?cid=65b708073fc0480ea92a077233ca87bd",
        "track_number": 1
    },
    "currently_playing_type": "track",
    "actions": {
        "disallows": [
            "toggling_repeat_track"
        ]
    }
}