theme = "dracula"
client_id = "${CLIENTID}"
client_port = 8080
playback_format = """


        {status} {track} • {artists}
        {album}
        {metadata}
        """
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Double"
cover_img_width = 7
cover_img_length = 16
cover_img_scale = 1.3
progress_bar_type = "Rectangle"
playback_window_width = 7
enable_cover_image_cache = true
default_device = "spotify-player"
seek_duration_secs = 5

[device]
name = "Rocinante"
device_type = "speaker"
volume = 60
bitrate = 320
audio_cache = false
normalization = false
autoplay = true

[layout]
library  = { album_percent = 40, playlist_percent = 40 }
playback_window_position = "Top"
playback_window_height = 11

