#!/bin/bash

log=~/.logs/DockerCleanup.log
date=$(date +%Y-%m-%d)

if [ ! -f $log ]; then
    touch $log
fi

echo "" >> $log
echo $date ": Start Log">> $log
docker image prune -af >> $log
echo $date ": End Log" >> $log
echo "" >> $log
