#!/bin/bash

while getopts ":m" opt; do
  case $opt in
    m)
      m=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Shift the parsed options to handle positional parameters correctly
shift $((OPTIND - 1))

if [ -z "$2" ] || [ "${#1}" -ne 6 ]; then
  echo "Usage: $0 [-m] <pair> <result>"
  echo "The pair should be a six-letter string."
  exit 1
fi


if [ "$m" = true ]; then
  display=$(xset q | grep -E 'Monitor is' | awk '{print $3}')
  echo "OFF"
  if [ $display = "On" ]; then
    exit 1
  fi
fi

m=false
pair="$1"
k="$2"
x="${pair:0:3}"
y="${pair: -3}"

response=$(curl -sL "https://api.kraken.com/0/public/Ticker?pair=$pair" -H 'Accept: application/json')

if [ $? -ne 0 ]; then
  echo "Failed to retrieve data from the Kraken API."
  exit 1
fi

error=$(echo "$response" | jq --arg k "$k" '.error[]')
rate_limit_error='EAPI:Rate limit exceeded'
throttled_error='EService: Throttled'

if [ "$error" == "$rate_limit_error" ]; then
  echo "Rate limit exceeded. Please try again later."
  exit 1
elif [ "$error" == "${throttled_error}:"* ]; then
  timestamp=$(echo "$error" | cut -d: -f3)
  echo "Too many concurrent requests. Try again after $timestamp."
  exit 1
fi

c=$(echo "$response" | jq --arg k "$k" '.result[$k]')

if [ $? -ne 0 ]; then
  echo "Failed to extract the required value from the JSON response."
  exit 1
fi

echo $c > ./assets/$pair
echo $c
exit 0
