#!/bin/bash

# Requires bc

# Made by Elizabeth Swann
# Tool to display crypto prices in i3bar
# Usage: ./krakenprice <PAIR> <PAIRKEY>
# You'll need to get the pair key from Kraken's website

if [ -z "$2" ] || [ "${#1}" -ne 6 ]; then
  echo "Usage: $0 <pair> <result>"
  echo "The pair should be a six-letter string."
  exit 1
fi

pair="$1"
k="$2"
x="${pair:0:3}"
y="${pair: -3}"

response=$(curl -sL "https://api.kraken.com/0/public/Ticker?pair=$pair" -H 'Accept: application/json')

if [ $? -ne 0 ]; then
  echo "Failed to retrieve data from the Kraken API."
  exit 1
fi

c=$(echo "$response" | jq --arg k "$k" '.result[$k]')


if [ $? -ne 0 ]; then
  echo "Failed to extract the required value from the JSON response."
  exit 1
fi

#echo $c | bc -l | xargs printf "%.2f\n"
printf "%.2f\n" $c
exit 0