#!/bin/bash

spotify_data=$(spotify_player get key playback)

album=$(echo $spotify_data | jq -r '.item.album.name')
artist=$(echo $spotify_data | jq -r '.item.artists[].name')
track=$(echo $spotify_data | jq -r '.item.name')

declare -a array
case ${#artist[@]} in 
    [1])
      artists="${artist[1]}"

    ;;
    [0])
      echo 
    ;;
esac

echo "Artist: "$artist
echo "Track: "$track
echo "Album: "$album