#!/bin/bash

CITY="Calgary"
API_KEY=$(cat ~/.config/environment/OpenWeatherMap)
GET=0

while getopts "g" opt; do
    case $opt in
      g) GET=1;;
      \?)exit 1;;
    esac
done

if [ "$GET" == "1" ]; then
    wget -qO- "https://api.openweathermap.org/data/2.5/weather?q=$CITY&appid=$API_KEY&units=metric" > ~/.logs/weather.json
    exit 0
else 
    echo $(cat ~/.logs/weather.json | jq -r '.weather[].description') $(cat ~/.logs/weather.json | jq -r '.main.temp') "| Feels Like:" $(cat ~/.logs/weather.json | jq -r '.main.feels_like') 
    exit 0
fi



